changess

diff --git a/res/DEBIAN/postinst b/res/DEBIAN/postinst
--- a/res/DEBIAN/postinst
+++ b/res/DEBIAN/postinst
@@ -5,25 +5,27 @@ set -e
 if [ "$1" = configure ]; then
 
 	INITSYS=$(ls -al /proc/1/exe | awk -F' ' '{print $NF}' | awk -F'/' '{print $NF}')
-	ln -f -s /usr/share/rustdesk/rustdesk /usr/bin/rustdesk
+	ln -f -s /usr/share/ez2desk/ez2desk /usr/bin/ez2desk
+	rm -f /usr/bin/rustdesk
 	
 	if [ "systemd" == "$INITSYS" ]; then
 
-		if [ -e /etc/systemd/system/rustdesk.service ]; then
-			rm /etc/systemd/system/rustdesk.service /usr/lib/systemd/system/rustdesk.service /usr/lib/systemd/user/rustdesk.service >/dev/null  2>&1
+		if [ -e /etc/systemd/system/rustdesk.service ] || [ -e /etc/systemd/system/ez2desk.service ]; then
+			rm /etc/systemd/system/rustdesk.service /usr/lib/systemd/system/rustdesk.service /usr/lib/systemd/user/rustdesk.service >/dev/null  2>&1 || true
+			rm /etc/systemd/system/ez2desk.service /usr/lib/systemd/system/ez2desk.service /usr/lib/systemd/user/ez2desk.service >/dev/null  2>&1 || true
 		fi
 		version=$(python3 -V 2>&1 | grep -Po '(?<=Python )(.+)')
 		parsedVersion=$(echo "${version//./}")
         mkdir -p /usr/lib/systemd/system/
-		cp /usr/share/rustdesk/files/systemd/rustdesk.service /usr/lib/systemd/system/rustdesk.service
+		cp /usr/share/ez2desk/files/systemd/ez2desk.service /usr/lib/systemd/system/ez2desk.service
 		# try fix error in Ubuntu 18.04
-		# Failed to reload rustdesk.service: Unit rustdesk.service is not loaded properly: Exec format error.
-		# /usr/lib/systemd/system/rustdesk.service:10: Executable path is not absolute: pkill -f "rustdesk --"
+		# Failed to reload ez2desk.service: Unit ez2desk.service is not loaded properly: Exec format error.
+		# /usr/lib/systemd/system/ez2desk.service:10: Executable path is not absolute: pkill -f "ez2desk --"
 		if [ -e /usr/bin/pkill ]; then
-			sed -i "s|pkill|/usr/bin/pkill|g" /usr/lib/systemd/system/rustdesk.service
+			sed -i "s|pkill|/usr/bin/pkill|g" /usr/lib/systemd/system/ez2desk.service
 		fi
 		systemctl daemon-reload
-		systemctl enable rustdesk
-		systemctl start rustdesk
+		systemctl enable ez2desk
+		systemctl start ez2desk
 	fi
 fi
